#!/bin/sh
#
# Copyright (C) 2001-2011 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Start GNU Chess, but have it use the xboard protocol.
# This makes it easy for programs (like xboard) to simply invoke
# "gnuchessx" and have it do the "right thing."

# The final parameter is more complicated to work around a
# bug in some old Unix-like systems; see the GNU autoconf documentation
# for the rationale.

gnuchess --xboard ${1+"$@"}

